//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegimenesEspeciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripción
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inscripción()
        {
            this.Contribución = new HashSet<Contribución>();
        }
    
        public int IdInscrip { get; set; }
        public string IdCI { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> IdActiv { get; set; }
        public Nullable<System.DateTime> FechaBEstatal { get; set; }
        public Nullable<System.DateTime> FechaOTierra { get; set; }
        public Nullable<bool> PagoR { get; set; }
        public Nullable<int> Plan { get; set; }
        public Nullable<int> Real { get; set; }
        public Nullable<int> CtadCiclico { get; set; }
        public Nullable<int> CausaBaja { get; set; }
        public string OtraCausaBaja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contribución> Contribución { get; set; }
        public virtual DPersonales DPersonales { get; set; }
        public virtual N_Acividad N_Acividad { get; set; }
    }
}
