//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegimenesEspeciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNom
    {
        public int IdMNom { get; set; }
        public int Actividad { get; set; }
        public int Tipo { get; set; }
        public int BaseC { get; set; }
        public int Estado { get; set; }
        public int Régimen { get; set; }
        public int Provincia { get; set; }
        public int Municipio { get; set; }
        public int Cooperativas { get; set; }
        public int Baja { get; set; }
    }
}
