//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegimenesEspeciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class N_BaseC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public N_BaseC()
        {
            this.Contribución = new HashSet<Contribución>();
        }
    
        public int IdBase { get; set; }
        public string Descripbase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contribución> Contribución { get; set; }
    }
}
