//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegimenesEspeciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NNotificación
    {
        public int IdNotif { get; set; }
        public string idCI { get; set; }
        public string DesNotif { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdRégimenOld { get; set; }
        public Nullable<int> IdRégimenNew { get; set; }
        public string Cod_MunOld { get; set; }
        public string Cod_MunNew { get; set; }
        public string CiOld { get; set; }
        public string CiNew { get; set; }
    }
}
