//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegimenesEspeciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyIcons
    {
        public int Id { get; set; }
        public string BalloonTipText { get; set; }
        public string BalloonTipTitle { get; set; }
        public int tiempo { get; set; }
        public Nullable<int> BallonTipIcon { get; set; }
        public int IdRégimen { get; set; }
    }
}
