//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegimenesEspeciales.Contexto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegUsu_devEntities1 : DbContext
    {
        public RegUsu_devEntities1()
            : base("name=RegUsu_devEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aut> Aut { get; set; }
        public virtual DbSet<Contribución> Contribución { get; set; }
        public virtual DbSet<Cooperativas> Cooperativas { get; set; }
        public virtual DbSet<coopPruebas> coopPruebas { get; set; }
        public virtual DbSet<DPersonales> DPersonales { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<Inscripción> Inscripción { get; set; }
        public virtual DbSet<MNom> MNom { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<N_Acividad> N_Acividad { get; set; }
        public virtual DbSet<N_BaseC> N_BaseC { get; set; }
        public virtual DbSet<N_Tipo> N_Tipo { get; set; }
        public virtual DbSet<NEstado> NEstado { get; set; }
        public virtual DbSet<NNotificación> NNotificación { get; set; }
        public virtual DbSet<NotifyIcons> NotifyIcons { get; set; }
        public virtual DbSet<NRégimen> NRégimen { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Salario> Salario { get; set; }
        public virtual DbSet<TiempoServicio> TiempoServicio { get; set; }
        public virtual DbSet<TipoAutenticación> TipoAutenticación { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<N_Baja> N_Baja { get; set; }
        public virtual DbSet<Usu_Eliminados> Usu_Eliminados { get; set; }
        public virtual DbSet<VersiónS> VersiónS { get; set; }
        public virtual DbSet<HistorialContribución> HistorialContribución { get; set; }
    }
}
