//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegimenesEspeciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salario
    {
        public int IdSalario { get; set; }
        public string IdCi { get; set; }
        public decimal Salario1 { get; set; }
        public string Año { get; set; }
    
        public virtual DPersonales DPersonales { get; set; }
    }
}
