//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegimenesEspeciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiempoServicio
    {
        public int IdTS { get; set; }
        public string IdCi { get; set; }
        public System.DateTime Desde { get; set; }
        public System.DateTime Hasta { get; set; }
        public int IdTipo { get; set; }
    
        public virtual DPersonales DPersonales { get; set; }
        public virtual N_Tipo N_Tipo { get; set; }
    }
}
