//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegimenesEspeciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usu_Eliminados
    {
        public string CI { get; set; }
        public string Nombre { get; set; }
        public string Apll { get; set; }
        public string Apll2 { get; set; }
        public string IdMun { get; set; }
        public System.DateTime Fecha { get; set; }
        public string AutoriMunicipio { get; set; }
        public string AutoriNación { get; set; }
    }
}
