//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegimenesEspeciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IdUser { get; set; }
        public string Usuario { get; set; }
        public string Pass { get; set; }
        public string IdProv { get; set; }
        public string IdMun { get; set; }
        public string IdGrupo { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Grupos Grupos { get; set; }
        public virtual Municipios Municipios { get; set; }
        public virtual Provincias Provincias { get; set; }
    }
}
